Fixes errors present in some samples in Kotlin
BrightcoveOS/android-player-samples pull request #301
Opened 2024-07-24 23:10 UTC by nandovelazquez

This PR includes fixes for #299. Also, it uses Brightcove SDK v9.1.0.

2024-07-24 23:16 UTC, KEAMCRF requested changes
We should add them to the README file

2024-07-25 15:40 UTC, nandovelazquez commented
> We should add them to the README file

I just updated that file, including the new apps, and added others that were missing.

2024-07-25 15:54 UTC, jrw95 approved these changes
LGTM

2024-07-25 16:21 UTC, KEAMCRF approved these changes

2024-07-26 15:00 UTC, merged